# Generated by Django 4.0.6 on 2022-09-02 23:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('api_url', models.URLField()),
                ('api_key', models.TextField()),
                ('request_delay', models.DecimalField(decimal_places=4, default=0.5, max_digits=5)),
                ('num_request_attempts', models.PositiveIntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='APIRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.utcnow)),
                ('status', models.CharField(choices=[('waiting', 'waiting'), ('finished', 'finished'), ('error', 'error')], default='waiting', max_length=20)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.api')),
            ],
        ),
    ]
