# Generated by Django 4.0.6 on 2022-09-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
