# Generated by Django 4.0.6 on 2022-09-02 23:59

from django.db import migrations, models
import django.db.models.deletion
import routing.model_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('street', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
            options={
                'unique_together': {('street', 'city', 'state', 'postal_code', 'country')},
            },
        ),
        migrations.CreateModel(
            name='AddressConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avoid_highways', models.BooleanField(default=False)),
                ('avoid_tolls', models.BooleanField(default=False)),
                ('avoid_ferries', models.BooleanField(default=True)),
                ('distance_meters', models.PositiveIntegerField()),
                ('travel_seconds', models.PositiveIntegerField()),
                ('from_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_address', to='routing.address')),
                ('to_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_address', to='routing.address')),
            ],
            options={
                'unique_together': {('from_address', 'to_address', 'avoid_highways', 'avoid_tolls', 'avoid_ferries')},
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route_key', models.CharField(default=routing.model_utils.route_get_unique_key, max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RouteAddressConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('address_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_connection', to='routing.addressconnection')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route', to='routing.route')),
            ],
        ),
    ]
